### ISSUE TITLE
编译send.cc时error: no matching function for call to ‘std::thread::thread(<unresolved overloaded function type>, int&, int&, __u32*&, int&, int&, int&, int&)’

### ISSUE THREAD

**Issue by shenbc** [shenbc/test_send_c#9]
thread_pool[i] = new std::thread(_thread_send_gradients, i, thread_num, tensor_array, array_len, str_dst_ip, worker_id, aggregator_index, tensor_index);行增加 str_dst_ip, worker_id, aggregator_index, tensor_index几个参数报错
~~~
sdn@server08:~/bc/test_send$ ./compile.sh
send.cc: In function ‘void multiple_threads_send_gradient(__u32*, int, int, unsigned int, int, int, int)’:
send.cc:88:171: error: no matching function for call to ‘std::thread::thread(<unresolved overloaded function type>, int&, int&, __u32*&, int&, int&, int&, int&)’
         thread_pool[i] = new std::thread(_thread_send_gradients, i, thread_num, tensor_array, array_len,/* str_dst_ip.c_str(),*/ worker_id, aggregator_index, tensor_index);
                                                                                                                                                                           ^
In file included from send.h:10:0,
                 from send.cc:1:
/usr/include/c++/7/thread:118:7: note: candidate: template<class _Callable, class ... _Args> std::thread::thread(_Callable&&, _Args&& ...)
       thread(_Callable&& __f, _Args&&... __args)
       ^~~~~~
/usr/include/c++/7/thread:118:7: note:   template argument deduction/substitution failed:
send.cc:88:171: note:   couldn't deduce template parameter ‘_Callable’
         thread_pool[i] = new std::thread(_thread_send_gradients, i, thread_num, tensor_array, array_len,/* str_dst_ip.c_str(),*/ worker_id, aggregator_index, tensor_index);
                                                                                                                                                                           ^
In file included from send.h:10:0,
                 from send.cc:1:
/usr/include/c++/7/thread:113:5: note: candidate: std::thread::thread(std::thread&&)
     thread(thread&& __t) noexcept
     ^~~~~~
/usr/include/c++/7/thread:113:5: note:   candidate expects 1 argument, 8 provided
/usr/include/c++/7/thread:106:5: note: candidate: std::thread::thread()
     thread() noexcept = default;
     ^~~~~~
/usr/include/c++/7/thread:106:5: note:   candidate expects 0 arguments, 8 provided
~~~

**Comment by shenbc** [comment]
将函数名_thread_send_gradients前下划线去掉后，可传入其他参数，编译正常。
可能是默认带下划线的为重载？

**Comment by shenbc** [comment]
send.py中cdll调用send.so：
~~~
usr@server08:~/bc/test_send$ sudo python3 tests/send.py
Traceback (most recent call last):
  File "tests/send.py", line 23, in <module>
    c_int
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: ./send.so: undefined symbol: multiple_threads_send_gradient
~~~
